### PR TITLE
fix: Add Berwick-upon-Tweed "m" for Alison

### PR DESCRIPTION
**Pull request by Muzer**
For some reason Berwick-upon-Tweed has only an "e" variant, so use the generic "Berwick" for both.

### CODE REVIEW

**Comment by davwheat** [comment]
Any chance you could do some simple demos of how the `e/BWK` would sound in place of the missing `m/BWK` file? Not near my PC or I'd do that myself.

**Comment by Muzer** [comment]
> Any chance you could do some simple demos of how the `e/BWK` would sound in place of the missing `m/BWK` file? Not near my PC or I'd do that myself.

I did consider that, I didn't think it would sound good but I didn't actually test it. Testing it now it indeed doesn't sound right; not quite as bad as I thought but I still don't like it. See what you think. https://tim32.org/~muzer/berwick-example.wav

**Comment by Muzer** [comment]
@davwheat ^ in case you missed it

**Comment by davwheat** [comment]
Yeah, not great. I'll go with this instead then.

**Review by davwheat — APPROVED** [review]

**Pull request merged**
